apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: auth-db
data:
  POSTGRES_DB: authdb
  POSTGRES_USER: vishal
  POSTGRES_PASSWORD: vishal123
  create_table.sql: |
    CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100));
     


