apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: visdocker11/mywebapp:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: webapp-configmap
            - secretRef:
                name: webapp-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
                