apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    app: auth-db
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}       
      targetPort: {{ .Values.service.port }}  
      nodePort: {{ .Values.service.NodePort }}   
  type: {{ .Values.service.type }}